Add Azure icons
cycloidio/tfdocs pull request #18
Opened 2020-08-04 10:24 UTC by kerak19

2020-08-04 10:30 UTC, kerak19 commented
There's a lot of unrelated changes for other providers - should I ignore them and only have azure related changes?

2020-08-04 10:36 UTC, xescugc requested changes
For now just this.

2020-08-04 10:36 UTC, xescugc commented on assets/azurerm/icons.json
> + "azurerm_application_insights": "Management + Governance/00012-icon-service-Application-Insights.svg",
Format the names to not have spaces or characters. so basically `Management_and_Governance`

2020-08-04 10:36 UTC, xescugc commented on assets/azurerm/icons.json
> + "azurerm_search_service": "App Services/10044-icon-service-Search-Services.svg",
`App_Service`.

2020-08-04 10:56 UTC, kerak19 commented
Done

2020-08-05 08:23 UTC, xescugc reviewed
RS

2020-08-05 08:45 UTC, kerak19 commented
Done

2020-08-05 12:52 UTC, xescugc approved these changes

2020-08-05 13:14 UTC, merged